# List of dependecies for ExecutionHook controller 

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

# The dependency on external-provisioner should be removed with #60.
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
  [[prune.project]]
    # Scripts under code-generator are required to generate code
    # when APIs are changed. Therefore they should not be pruned.
    name = "k8s.io/code-generator"
    non-go = false
    unused-packages = false
