/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-csi/execution-hook/pkg/apis/executionhook/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExecutionHookTemplates implements ExecutionHookTemplateInterface
type FakeExecutionHookTemplates struct {
	Fake *FakeExecutionhookV1alpha1
	ns   string
}

var executionhooktemplatesResource = schema.GroupVersionResource{Group: "executionhook", Version: "v1alpha1", Resource: "executionhooktemplates"}

var executionhooktemplatesKind = schema.GroupVersionKind{Group: "executionhook", Version: "v1alpha1", Kind: "ExecutionHookTemplate"}

// Get takes name of the executionHookTemplate, and returns the corresponding executionHookTemplate object, and an error if there is any.
func (c *FakeExecutionHookTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.ExecutionHookTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(executionhooktemplatesResource, c.ns, name), &v1alpha1.ExecutionHookTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHookTemplate), err
}

// List takes label and field selectors, and returns the list of ExecutionHookTemplates that match those selectors.
func (c *FakeExecutionHookTemplates) List(opts v1.ListOptions) (result *v1alpha1.ExecutionHookTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(executionhooktemplatesResource, executionhooktemplatesKind, c.ns, opts), &v1alpha1.ExecutionHookTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExecutionHookTemplateList{ListMeta: obj.(*v1alpha1.ExecutionHookTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExecutionHookTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested executionHookTemplates.
func (c *FakeExecutionHookTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(executionhooktemplatesResource, c.ns, opts))

}

// Create takes the representation of a executionHookTemplate and creates it.  Returns the server's representation of the executionHookTemplate, and an error, if there is any.
func (c *FakeExecutionHookTemplates) Create(executionHookTemplate *v1alpha1.ExecutionHookTemplate) (result *v1alpha1.ExecutionHookTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(executionhooktemplatesResource, c.ns, executionHookTemplate), &v1alpha1.ExecutionHookTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHookTemplate), err
}

// Update takes the representation of a executionHookTemplate and updates it. Returns the server's representation of the executionHookTemplate, and an error, if there is any.
func (c *FakeExecutionHookTemplates) Update(executionHookTemplate *v1alpha1.ExecutionHookTemplate) (result *v1alpha1.ExecutionHookTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(executionhooktemplatesResource, c.ns, executionHookTemplate), &v1alpha1.ExecutionHookTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHookTemplate), err
}

// Delete takes name of the executionHookTemplate and deletes it. Returns an error if one occurs.
func (c *FakeExecutionHookTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(executionhooktemplatesResource, c.ns, name), &v1alpha1.ExecutionHookTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExecutionHookTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(executionhooktemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExecutionHookTemplateList{})
	return err
}

// Patch applies the patch and returns the patched executionHookTemplate.
func (c *FakeExecutionHookTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExecutionHookTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(executionhooktemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExecutionHookTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHookTemplate), err
}
