/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-csi/execution-hook/pkg/apis/executionhook/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExecutionHooks implements ExecutionHookInterface
type FakeExecutionHooks struct {
	Fake *FakeExecutionhookV1alpha1
	ns   string
}

var executionhooksResource = schema.GroupVersionResource{Group: "executionhook", Version: "v1alpha1", Resource: "executionhooks"}

var executionhooksKind = schema.GroupVersionKind{Group: "executionhook", Version: "v1alpha1", Kind: "ExecutionHook"}

// Get takes name of the executionHook, and returns the corresponding executionHook object, and an error if there is any.
func (c *FakeExecutionHooks) Get(name string, options v1.GetOptions) (result *v1alpha1.ExecutionHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(executionhooksResource, c.ns, name), &v1alpha1.ExecutionHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHook), err
}

// List takes label and field selectors, and returns the list of ExecutionHooks that match those selectors.
func (c *FakeExecutionHooks) List(opts v1.ListOptions) (result *v1alpha1.ExecutionHookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(executionhooksResource, executionhooksKind, c.ns, opts), &v1alpha1.ExecutionHookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExecutionHookList{ListMeta: obj.(*v1alpha1.ExecutionHookList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExecutionHookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested executionHooks.
func (c *FakeExecutionHooks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(executionhooksResource, c.ns, opts))

}

// Create takes the representation of a executionHook and creates it.  Returns the server's representation of the executionHook, and an error, if there is any.
func (c *FakeExecutionHooks) Create(executionHook *v1alpha1.ExecutionHook) (result *v1alpha1.ExecutionHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(executionhooksResource, c.ns, executionHook), &v1alpha1.ExecutionHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHook), err
}

// Update takes the representation of a executionHook and updates it. Returns the server's representation of the executionHook, and an error, if there is any.
func (c *FakeExecutionHooks) Update(executionHook *v1alpha1.ExecutionHook) (result *v1alpha1.ExecutionHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(executionhooksResource, c.ns, executionHook), &v1alpha1.ExecutionHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExecutionHooks) UpdateStatus(executionHook *v1alpha1.ExecutionHook) (*v1alpha1.ExecutionHook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(executionhooksResource, "status", c.ns, executionHook), &v1alpha1.ExecutionHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHook), err
}

// Delete takes name of the executionHook and deletes it. Returns an error if one occurs.
func (c *FakeExecutionHooks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(executionhooksResource, c.ns, name), &v1alpha1.ExecutionHook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExecutionHooks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(executionhooksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExecutionHookList{})
	return err
}

// Patch applies the patch and returns the patched executionHook.
func (c *FakeExecutionHooks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExecutionHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(executionhooksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExecutionHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExecutionHook), err
}
