// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	storagev1 "k8s.io/api/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerExecutionHookStatus) DeepCopyInto(out *ContainerExecutionHookStatus) {
	*out = *in
	if in.PreActionStatus != nil {
		in, out := &in.PreActionStatus, &out.PreActionStatus
		*out = new(ExecutionHookActionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PostActionStatus != nil {
		in, out := &in.PostActionStatus, &out.PostActionStatus
		*out = new(ExecutionHookActionStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerExecutionHookStatus.
func (in *ContainerExecutionHookStatus) DeepCopy() *ContainerExecutionHookStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerExecutionHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHook) DeepCopyInto(out *ExecutionHook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHook.
func (in *ExecutionHook) DeepCopy() *ExecutionHook {
	if in == nil {
		return nil
	}
	out := new(ExecutionHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionHook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookAction) DeepCopyInto(out *ExecutionHookAction) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(v1.Handler)
		(*in).DeepCopyInto(*out)
	}
	if in.ActionTimeoutSeconds != nil {
		in, out := &in.ActionTimeoutSeconds, &out.ActionTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookAction.
func (in *ExecutionHookAction) DeepCopy() *ExecutionHookAction {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookActionStatus) DeepCopyInto(out *ExecutionHookActionStatus) {
	*out = *in
	if in.ActionTimestamp != nil {
		in, out := &in.ActionTimestamp, &out.ActionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ActionSucceed != nil {
		in, out := &in.ActionSucceed, &out.ActionSucceed
		*out = new(bool)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(storagev1.VolumeError)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookActionStatus.
func (in *ExecutionHookActionStatus) DeepCopy() *ExecutionHookActionStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookInfo) DeepCopyInto(out *ExecutionHookInfo) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSelector != nil {
		in, out := &in.ContainerSelector, &out.ContainerSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodContainerNamesList != nil {
		in, out := &in.PodContainerNamesList, &out.PodContainerNamesList
		*out = make([]PodContainerNames, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookInfo.
func (in *ExecutionHookInfo) DeepCopy() *ExecutionHookInfo {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookList) DeepCopyInto(out *ExecutionHookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExecutionHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookList.
func (in *ExecutionHookList) DeepCopy() *ExecutionHookList {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionHookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookSpec) DeepCopyInto(out *ExecutionHookSpec) {
	*out = *in
	if in.PodContainerNamesList != nil {
		in, out := &in.PodContainerNamesList, &out.PodContainerNamesList
		*out = make([]PodContainerNames, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSelector != nil {
		in, out := &in.ContainerSelector, &out.ContainerSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PreAction != nil {
		in, out := &in.PreAction, &out.PreAction
		*out = new(ExecutionHookAction)
		(*in).DeepCopyInto(*out)
	}
	if in.PostAction != nil {
		in, out := &in.PostAction, &out.PostAction
		*out = new(ExecutionHookAction)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpirationSeconds != nil {
		in, out := &in.ExpirationSeconds, &out.ExpirationSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookSpec.
func (in *ExecutionHookSpec) DeepCopy() *ExecutionHookSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookStatus) DeepCopyInto(out *ExecutionHookStatus) {
	*out = *in
	if in.ContainerExecutionHookStatuses != nil {
		in, out := &in.ContainerExecutionHookStatuses, &out.ContainerExecutionHookStatuses
		*out = make([]ContainerExecutionHookStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreActionSucceed != nil {
		in, out := &in.PreActionSucceed, &out.PreActionSucceed
		*out = new(bool)
		**out = **in
	}
	if in.PostActionSucceed != nil {
		in, out := &in.PostActionSucceed, &out.PostActionSucceed
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookStatus.
func (in *ExecutionHookStatus) DeepCopy() *ExecutionHookStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookTemplate) DeepCopyInto(out *ExecutionHookTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(HookPolicy)
		**out = **in
	}
	if in.PreAction != nil {
		in, out := &in.PreAction, &out.PreAction
		*out = new(ExecutionHookAction)
		(*in).DeepCopyInto(*out)
	}
	if in.PostAction != nil {
		in, out := &in.PostAction, &out.PostAction
		*out = new(ExecutionHookAction)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpirationSeconds != nil {
		in, out := &in.ExpirationSeconds, &out.ExpirationSeconds
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookTemplate.
func (in *ExecutionHookTemplate) DeepCopy() *ExecutionHookTemplate {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionHookTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionHookTemplateList) DeepCopyInto(out *ExecutionHookTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExecutionHookTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionHookTemplateList.
func (in *ExecutionHookTemplateList) DeepCopy() *ExecutionHookTemplateList {
	if in == nil {
		return nil
	}
	out := new(ExecutionHookTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionHookTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodContainerNames) DeepCopyInto(out *PodContainerNames) {
	*out = *in
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodContainerNames.
func (in *PodContainerNames) DeepCopy() *PodContainerNames {
	if in == nil {
		return nil
	}
	out := new(PodContainerNames)
	in.DeepCopyInto(out)
	return out
}
