# This YAML file contains all RBAC objects that are necessary to run
# the hook controller.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook 

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # rename if there are conflicts
  name: hook-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]
  - apiGroups: ["apps.k8s.io"]
    resources: ["executionhooks"]
    verbs: ["create","get", "list", "watch", "update"]
  - apiGroups: ["apps.k8s.io"]
    resources: ["executionhooktemplates"]
    verbs: ["create","get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hook-role
subjects:
  - kind: ServiceAccount
    name: hook
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  # change the name also here if the ClusterRole gets renamed
  name: hook-runner
  apiGroup: rbac.authorization.k8s.io
