apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-hostpath-sc # defined in csi-setup.yaml
